name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        ruby-version: ['3.1', '3.0', '2.7', 'jruby']
        rails-version: [edge, '7.0', '6.1', '6.0']
        test-suite: ['', 'templates:test']

        exclude:
          - ruby-version: '3.1'
            rails-version: '6.0'
          - ruby-version: 'jruby'
            rails-version: 'edge'

        include:
          - ruby-version: 'ruby-head'
            rails-version: 'edge'

          - ruby-version: '2.6'
            rails-version: '6.1'
          - ruby-version: '2.6'
            rails-version: '6.0'

          - ruby-version: '2.5'
            rails-version: '6.1'
          - ruby-version: '2.5'
            rails-version: '6.0'

    env:
      RAILS_VERSION: ${{ matrix.rails-version }}

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        continue-on-error: ${{ (matrix.ruby-version == 'ruby-head') || (matrix.ruby-version == 'jruby') || (matrix.rails-version == 'edge') }}
      - run: bundle exec rake test ${{ matrix.test-suite }}
        continue-on-error: ${{ (matrix.ruby-version == 'ruby-head') || (matrix.ruby-version == 'jruby') || (matrix.rails-version == 'edge') }}
